### ISSUE TITLE
dataset download always times out

### ISSUE THREAD

**Issue by jere1882** [PolymathicAI/AstroCLIP#18]
The instruction in Readme say to use hugging face interface to download:

 dset = load_dataset('astroclip/data/dataset.py'

This **always** fails with a timeout error shortly after starting the download.

```
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
(...)
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
```

there are many reports across the web about OpenSLR having timeout issues, can you please provide an alternative to download the data?

**Comment by lsarra** [comment]
Hi, thank you for pointing this out! I believe the problem is when downloading from different servers from HuggingFace (we are not using OpenSLR but the internal Flatiron server). I tested it with extra timeout and now it does not seem to crash anymore (see PR #19).

Otherwise, you can manually download it from https://users.flatironinstitute.org/~flanusse/astroclip_desi.1.1.5.h5, e.g.
```
wget  https://users.flatironinstitute.org/~flanusse/astroclip_desi.1.1.5.h5
```

Then, if you stored it in `PATH`, you could change the code in `astroclip/data/dataset.py`
https://github.com/PolymathicAI/AstroCLIP/blob/e26c3704f32b35acc13bc462d95739ece41a23ea/astroclip/data/dataset.py#L78

to 
```python
data_dir = dl_manager.extract(PATH) 
```

**Comment by EiffL** [comment]
#19 solves this issue, thanks for reporting it! And thanks @lsarra for implementing a fix
